// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmphU4NwDnAjcyCLPglIM3ybNxXwjoZNY',
    appId: '1:957472013508:android:7380486c849cc4e3015d91',
    messagingSenderId: '957472013508',
    projectId: 'bloomapp-f4a5b',
    databaseURL: 'https://bloomapp-f4a5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloomapp-f4a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDidR2gmTY2mSLgejhvmrJHMMBr_9vuXZk',
    appId: '1:957472013508:ios:0b70a5e5a111d617015d91',
    messagingSenderId: '957472013508',
    projectId: 'bloomapp-f4a5b',
    databaseURL: 'https://bloomapp-f4a5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloomapp-f4a5b.firebasestorage.app',
    iosBundleId: 'com.example.bloomiot',
  );
}
